dataset: 
  images_root: "../datasets/celebamaskhq_identity_dataset/imgs" # The clean images root directory
  annotations: "../files/celeb_anno.json"
  dataset_name: "celebamaskhq" # dataset name for creating cache directory. in ["celebamaskhq_align", "fiw_align"]
  cache_dir: "../latent_cache" # root cache directory
  attribute_path: "../files/attributes.json" # age, gender, race for each image
  id_attribute_path: "../files/id_attributes.json" # gender and race for each id
  target_path: "../files/target/085807.jpg"
  test_path: "../files/test/047073.jpg"
  auto_prompt: 0
  target_prompt: "A young Caucasian woman in her late teens to early twenties, with clear light skin and subtle freckles, large almond-shaped brown eyes, thick dark slightly arched eyebrows, an oval-shaped face with smooth contours, a straight nose, and medium-full well-defined lips."
  prompt_type: "gender" # two styles: ["gender", "age_gender_race", "face"]
  train_set_size: 8 # size of trainset of each identity
  num_train_ids: 100 # number of identities to include in the datasets
  identity_start_idx: 0 # full training set consists of the identities anno["victim_ids"][identity_start_idx: identity_start_idx+num_train_ids]
  num_id_in_group: 1
  res: 512 # Input image resized resolution

diffusion:
  pretrained_diffusion_path: "sd2-community/stable-diffusion-2-base"
  diffusion_steps: 20 # Total DDIM sampling steps
  num_fixed_point_iters: 6 # 6, 10 # number of maximum fixed-point iteration in AIDI
  start_step: 15 # 15, 10 # Which DDIM step at which to start the attack
  guidance_scale: 2.5 # guidance scale of diffusion models

training:
  seed: 42
  save_dir: "../logs" # Where to save the adversarial examples, and other results
  victim_model_dir: "./fr_models" # Path to definitions and checkpoints of victim models
  all_model_names: ['mobile_face', 'ir152', 'irse50', 'facenet']
  test_model_names: ['mobile_face', 'ir152', 'irse50', 'facenet'] # available models: ['mobile_face', 'ir152', 'irse50', 'facenet']
  surrogate_model_names: ['ir152', 'irse50', 'facenet'] # available models: ['mobile_face', 'ir152', 'irse50', 'facenet']
  optim_algo: "pgd" # choice of optimization algorithm from ['adamw', 'adam', 'pgd', "mifgsm"]
  memory_efficient: 1 # use memory efficient gradient algo
  monitor_memory: 0
  lr: 0.025 # learning rate
  warm_up_steps: 8 
  weight_decay: 0.001 # weight decay for adamw
  pgd_radius: 2.0 # the radius constrain for PGD optimization
  momentum: 1.0
  batch_size: 1 # training batch size
  total_update_steps: 80 # 64 # total_update_steps = n_epoch * (train_set_size // batch_size)
  attack_loss_weight: 10 # 10 # attack loss weight factor
  ca_loss_is_targeted: 1 # 1 for targetd and 0 for untargeted
  cross_attn_loss_weight: 20000 # 10000 # targeted cross attention loss weight factor.
  cross_attn_reg_weight: 3000
  words: []
  self_attn_loss_weight: 0 # 1000 # 4000 # 2000 # 1000 # self attention loss weight factors
  ca_loss_is_w_ends: 1 # whether to include the start of text and end of text tokens in the targeted ca loss calculation
  kl_3d: 0 # use 3d kl-divergence over the whole attmap, instead of per pixel
  use_mse: 1